begin;

create schema if not exists iam;
create schema if not exists configuration;
create schema if not exists monitoring;
create schema if not exists integration;

create table if not exists iam.app_user (
    user_id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    display_name varchar(100) not null,
    password_hash text not null,
    active boolean not null default true,
    first_login boolean not null default true,
    employee_id varchar(32),
    department_name varchar(128),
    email varchar(254),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists iam.app_role (
    role_code varchar(32) primary key,
    display_name varchar(64) not null,
    description text
);

create table if not exists iam.user_role (
    user_id bigint not null references iam.app_user(user_id) on delete cascade,
    role_code varchar(32) not null references iam.app_role(role_code),
    primary key (user_id, role_code)
);

create table if not exists configuration.po_server (
    sid varchar(8) primary key,
    display_name varchar(100) not null,
    environment varchar(16) not null
        check (environment in ('production', 'quality', 'development', 'sandbox')),
    base_url text not null,
    port integer not null default 50000 check (port between 1 and 65535),
    capabilities jsonb not null default '[]'::jsonb,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists iam.user_server (
    user_id bigint not null references iam.app_user(user_id) on delete cascade,
    sid varchar(8) not null references configuration.po_server(sid) on delete cascade,
    primary key (user_id, sid)
);

create table if not exists monitoring.message_recent (
    sid varchar(8) not null references configuration.po_server(sid),
    message_id varchar(128) not null,
    interface_name varchar(256) not null,
    namespace text not null,
    status varchar(24) not null,
    start_time timestamptz not null,
    end_time timestamptz,
    duration_ms bigint,
    size_bytes bigint,
    error_text text,
    collected_at timestamptz not null default now(),
    primary key (sid, message_id)
);

create index if not exists ix_message_recent_start_time
    on monitoring.message_recent (start_time desc);

create table if not exists monitoring.incident_history (
    incident_key varchar(256) primary key,
    incident_type varchar(32) not null,
    sid varchar(8) not null references configuration.po_server(sid),
    message_id varchar(128) not null,
    interface_name varchar(256) not null,
    status varchar(24) not null,
    first_seen_at timestamptz not null,
    last_seen_at timestamptz not null,
    resolved_at timestamptz,
    resolved_by bigint references iam.app_user(user_id),
    detail jsonb
);

create table if not exists monitoring.collector_checkpoint (
    sid varchar(8) primary key references configuration.po_server(sid),
    last_window_end timestamptz,
    last_message_id varchar(128),
    last_success_at timestamptz,
    status varchar(24) not null,
    item_count bigint not null default 0,
    elapsed_ms bigint not null default 0,
    detail text
);

insert into iam.app_role (role_code, display_name, description) values
    ('ADMIN', '관리자', '전체 설정 및 운영 권한'),
    ('OPERATOR', '운영자', '조회 및 운영 작업 권한'),
    ('VIEWER', '조회자', '조회 전용 권한')
on conflict (role_code) do nothing;

commit;
