begin;

create table if not exists iam.dashboard_preference (
    user_id bigint primary key references iam.app_user(user_id) on delete cascade,
    layout jsonb not null,
    updated_at timestamptz not null default now()
);

create table if not exists monitoring.alert_event (
    alert_id bigint generated by default as identity primary key,
    sid varchar(8) not null references configuration.po_server(sid),
    domain_name varchar(64) not null,
    alert_code varchar(128) not null,
    title varchar(256) not null,
    detail text,
    severity varchar(16) not null
        check (severity in ('critical', 'warning', 'info')),
    status varchar(16) not null default 'open'
        check (status in ('open', 'acknowledged', 'resolved')),
    occurred_at timestamptz not null,
    acknowledged_at timestamptz,
    acknowledged_by bigint references iam.app_user(user_id),
    resolved_at timestamptz,
    context jsonb not null default '{}'::jsonb
);

create index if not exists ix_alert_event_sid_status_occurred_at
    on monitoring.alert_event (sid, status, occurred_at desc);

create table if not exists integration.llm_search_history (
    search_id bigint generated by default as identity primary key,
    user_id bigint not null references iam.app_user(user_id),
    alert_id bigint references monitoring.alert_event(alert_id),
    question text not null,
    answer text,
    source_refs jsonb not null default '[]'::jsonb,
    status varchar(24) not null,
    created_at timestamptz not null default now()
);

commit;
