begin;

create schema if not exists workspace;

create table if not exists workspace.project_workspace (
    workspace_id bigint generated by default as identity primary key,
    owner_id bigint not null references iam.app_user(user_id) on delete cascade,
    task_name varchar(160) not null,
    description text,
    progress smallint not null default 0 check (progress between 0 and 100),
    status varchar(24) not null default 'planned'
        check (status in ('planned', 'in_progress', 'review', 'completed')),
    target_date date,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists ix_project_workspace_owner_updated
    on workspace.project_workspace (owner_id, updated_at desc);

commit;
