begin;

create table if not exists configuration.monitoring_policy (
    sid varchar(8) primary key,
    response_window_minutes integer not null default 15
        check (response_window_minutes between 5 and 1440),
    slow_threshold_ms integer not null default 3000
        check (slow_threshold_ms between 100 and 3600000),
    critical_threshold_ms integer not null default 10000
        check (critical_threshold_ms >= slow_threshold_ms),
    max_detail_rows integer not null default 100
        check (max_detail_rows between 10 and 500),
    updated_by varchar(64),
    updated_at timestamptz not null default now()
);

create table if not exists iam.access_audit (
    audit_id bigint generated by default as identity primary key,
    actor_username varchar(64) not null,
    target_username varchar(64) not null,
    action varchar(32) not null,
    detail jsonb not null default '{}'::jsonb,
    occurred_at timestamptz not null default now()
);

create index if not exists ix_access_audit_occurred_at
    on iam.access_audit (occurred_at desc);

update iam.app_role set display_name = 'admin', description = '사용자·환경 설정을 포함한 전체 권한'
where role_code = 'ADMIN';
update iam.app_role set display_name = '관리자', description = '모니터링 조회와 채널 운영 권한'
where role_code = 'OPERATOR';
update iam.app_role set display_name = '일반', description = '모니터링과 Audit 조회 전용 권한'
where role_code = 'VIEWER';

commit;
