begin;

create schema if not exists knowledge;
create schema if not exists operations;

create table if not exists knowledge.post (
    post_id bigint generated by default as identity primary key,
    author_username varchar(64) not null,
    title varchar(200) not null,
    content text not null,
    category varchar(64) not null default 'GENERAL',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists ix_post_updated_at
    on knowledge.post (updated_at desc);

create table if not exists iam.password_reset_request (
    request_id bigint generated by default as identity primary key,
    username varchar(64) not null,
    token_hash varchar(64) not null unique,
    expires_at timestamptz not null,
    used_at timestamptz,
    requested_at timestamptz not null default now()
);

create index if not exists ix_password_reset_username
    on iam.password_reset_request (username, requested_at desc);

create table if not exists operations.oracle_ifs_cache (
    req_seq varchar(128) primary key,
    eai_dev_user_id varchar(128),
    ifs_ids text[] not null default array[]::text[],
    source_system varchar(128),
    source_adapter varchar(128),
    target_system varchar(128),
    target_adapter varchar(128),
    progress_status varchar(64),
    process_date date,
    target_date date,
    synced_at timestamptz not null default now()
);

create index if not exists ix_oracle_ifs_cache_user
    on operations.oracle_ifs_cache (lower(eai_dev_user_id));

create table if not exists operations.oracle_ifs_sync_log (
    sync_id bigint generated by default as identity primary key,
    status varchar(16) not null,
    row_count integer not null default 0,
    detail varchar(1000),
    started_at timestamptz not null default now(),
    completed_at timestamptz
);

commit;
